---
- name: adding network details
  blockinfile:
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    block: |
      network={
        ssid="{{ wifi_ssid }}"
        psk="{{ wifi_psk }}"
      }
  become: yes
  notify:
    - reboot
    - wait for reboot
