---
- name: install packages
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  become: yes
  with_items:
    - git
    - build-essential
    - autoconf
    - automake
    - libtool
    - libtool-bin
    - libevent-dev
    - libssl-dev
    - libgcrypt11-dev
    - libkrb5-dev
    - libpam0g-dev
    - libwrap0-dev
    - libdb-dev
    - libtdb-dev
    - libmysqlclient-dev
    - avahi-daemon
    - libavahi-client-dev
    - libacl1-dev
    - libldap2-dev
    - libcrack2-dev
    - systemtap-sdt-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libglib2.0-dev
    - tracker
    - libtracker-sparql-1.0-dev
    - libtracker-miner-1.0-dev

- name: check release
  get_url: url=https://sourceforge.net/projects/netatalk/best_release.json dest=~/netatalk.json force=yes
  register: source

- name: download
  git: repo=https://github.com/Netatalk/Netatalk.git dest=netatalk force=yes
  when: source.changed

- name: bootstrap build
  command: ./bootstrap chdir=netatalk
  when: source.changed

- name: configure build
  command: ./configure --with-init-style=debian-systemd --without-libevent --without-tdb --with-cracklib --enable-krbV-uam --with-pam-confdir=/etc/pam.d --with-dbus-sysconf-dir=/etc/dbus-1/system.d --with-tracker-pkgconfig-version=1.0 chdir=netatalk
  when: source.changed

- name: build
  command: make chdir=netatalk
  when: source.changed

- name: install
  command: make install chdir=netatalk
  become: yes
  when: source.changed
  notify:
    - reboot
    - wait for reboot

- name: enable avahi-daemon
  service: name=avahi-daemon enabled=yes
  become: yes

- name: enable
  service: name=netatalk enabled=yes
  become: yes

- name: configure
  template: src=afp.conf.j2 dest=/usr/local/etc/afp.conf
  become: yes
  notify:
    - reboot
    - wait for reboot
