---
- name: reboot
  shell: sleep 2 && reboot
  become: yes
  async: 1
  poll: 0

- name: wait for reboot
  local_action:
    module: wait_for
    host: "{{ ansible_host }}"
    port: 22
    delay: 2
