---
- name: install shairport-sync
  apt:
    name: shairport-sync
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: configure
  template:
    src: shairport-sync.conf.j2
    dest: /etc/shairport-sync.conf
  become: yes
  notify:
    - reboot
    - wait for reboot
